### ISSUE TITLE
Add label rotation option

### ISSUE THREAD

**Issue by DanSleeman** [dchupp/printerEmulator#11]
Would be nice to have the ability to rotate the generated labels.
This functionality exists on the Labelary website which is pretty handy when sending quick screenshots or troubleshooting layout issues.

**Comment by dchupp** [comment]
@DanSleeman - What a great idea! I'll try to add that this evening.

**Comment by dchupp** [comment]
It looks easy enough: 
5.1. Rotate labels
Your ZPL template already defines a label rotation / orientation. Sometimes, however, the label orientation that is most suitable for your printer is not the orientation that you'd like to use during format conversion.

If this is the case, you can ask Labelary to rotate the label image by adding a X-Rotation HTTP header to the request. The value of this header should be the number of degrees to rotate the label clockwise, and may be one of 0, 90, 180 or 270.

**Comment by dchupp** [comment]
@DanSleeman - added the rotate option to the emulator:
![image](https://github.com/user-attachments/assets/a21f2848-bc7a-424b-8221-a232c49d8b30)
